"""
MA Payer Platform - Readmission Analytics Dashboard.

Reads pre-materialized aggregate snapshots from streamlit/data/*.csv.
Snapshots are generated by scripts/export_snapshots.py running against
the dbt marts in Snowflake (MA_PAYER.MARTS).

Architecture separates compute (Snowflake + dbt, runs on demand) from
presentation (this Streamlit app, reads committed snapshots). This keeps
the public deploy free of Snowflake credentials and independent of
Snowflake trial lifecycle.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

st.set_page_config(
    page_title="MA Payer Platform - Readmission Analytics",
    page_icon=":hospital:",
    layout="wide",
)

DATA_DIR = Path(__file__).resolve().parent / "data"


@st.cache_data(ttl=3600)
def _load(name: str) -> pd.DataFrame:
    path = DATA_DIR / f"{name}.csv"
    if not path.exists():
        st.error(
            f"Missing snapshot: {path.name}. "
            "Run `python scripts/export_snapshots.py` to generate it."
        )
        st.stop()
    return pd.read_csv(path)


st.title("MA Payer Platform - Readmission Analytics")
st.caption("Medicare Advantage analytics on CMS DE-SynPUF | Snowflake + dbt + Streamlit")

with st.sidebar:
    st.markdown("### About")
    st.markdown(
        "Portfolio project demonstrating end-to-end modern payer data stack: "
        "CMS synthetic claims through Snowflake and dbt into HEDIS-style measures."
    )
    st.markdown("### Source data")
    st.markdown(
        "**CMS DE-SynPUF Sample 1** - ~116K beneficiaries, ~67K inpatient admissions, "
        "2008-2010. Fully synthetic, no DUA required."
    )
    st.markdown("### Key measure")
    st.markdown(
        "**30-day all-cause readmission** - HEDIS-style proxy. "
        "Index admission + any admission within 30 days of discharge. "
        "Excludes transfers/interrupted stays."
    )
    st.markdown("### Architecture")
    st.markdown(
        "Snapshots pre-materialized from Snowflake marts. "
        "See [GitHub repo](https://github.com/nancytanaka1/ma-payer-platform) "
        "for source, dbt models, and reproduction steps."
    )

# KPI row
kpi = _load("headline").iloc[0]
c1, c2, c3, c4 = st.columns(4)
c1.metric("Index Admissions", f"{int(kpi['ELIGIBLE']):,}")
c2.metric("30-Day Readmissions", f"{int(kpi['READMISSIONS']):,}")
c3.metric("Readmit Rate", f"{float(kpi['READMIT_RATE_PCT']):.2f}%")
c4.metric("Avg Days to Readmit", f"{float(kpi['AVG_DAYS_READMIT']):.1f}")

st.divider()

# Chronic cohort bar chart
st.subheader("Readmission Rate by Chronic Condition Cohort")
st.caption("Members can belong to multiple cohorts - rates do not sum")
chronic = _load("chronic")
chronic["RATE"] = chronic["RATE"].astype(float)
fig1 = px.bar(
    chronic, x="COHORT", y="RATE", text="RATE", color="RATE",
    color_continuous_scale="Reds",
    labels={"RATE": "30-Day Readmit Rate (%)", "COHORT": "Chronic Condition"},
    height=400,
)
fig1.update_traces(texttemplate="%{text:.1f}%", textposition="outside")
fig1.update_layout(showlegend=False, yaxis_range=[0, float(chronic["RATE"].max()) * 1.2])
st.plotly_chart(fig1, use_container_width=True)

# Monthly trend
st.subheader("Monthly Admission Volume and Readmission Rate")
monthly = _load("monthly")
monthly["READMIT_RATE_PCT"] = monthly["READMIT_RATE_PCT"].astype(float)
monthly["MONTH"] = pd.to_datetime(monthly["MONTH"])
a, b = st.columns(2)
with a:
    fig2 = px.bar(monthly, x="MONTH", y="ADMISSIONS", height=350,
                  labels={"MONTH": "Month", "ADMISSIONS": "Index Admissions"})
    st.plotly_chart(fig2, use_container_width=True)
with b:
    fig3 = px.line(monthly, x="MONTH", y="READMIT_RATE_PCT", markers=True, height=350,
                   labels={"MONTH": "Month", "READMIT_RATE_PCT": "Readmit Rate (%)"})
    fig3.add_hline(y=float(kpi["READMIT_RATE_PCT"]), line_dash="dash", line_color="red",
                   annotation_text=f"Overall: {float(kpi['READMIT_RATE_PCT']):.2f}%")
    st.plotly_chart(fig3, use_container_width=True)

st.divider()
st.markdown(
    "Data: [CMS DE-SynPUF](https://www.cms.gov/data-research/statistics-trends-and-reports/"
    "medicare-claims-synthetic-public-use-files) (synthetic, no PHI) | "
    "Code: [github.com/nancytanaka1/ma-payer-platform]"
    "(https://github.com/nancytanaka1/ma-payer-platform)"
)
