-- Snowflake env setup + stage upload. Step 1 of 3.
-- Run via: snowsql -a <account> -u <user> -f sql/01_setup_and_stage.sql

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_XS
  WITH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS MA_PAYER;
USE DATABASE MA_PAYER;
CREATE SCHEMA IF NOT EXISTS RAW_SYNPUF;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MARTS;
USE SCHEMA RAW_SYNPUF;
USE WAREHOUSE WH_XS;

CREATE OR REPLACE FILE FORMAT FF_CSV_HEADER
  TYPE = 'CSV' PARSE_HEADER = TRUE FIELD_OPTIONALLY_ENCLOSED_BY = '"' FIELD_DELIMITER = ','
  NULL_IF = ('', 'NULL', 'null', 'NA') EMPTY_FIELD_AS_NULL = TRUE TRIM_SPACE = TRUE COMPRESSION = AUTO;

CREATE OR REPLACE FILE FORMAT FF_CSV_LOAD
  TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' FIELD_DELIMITER = ','
  NULL_IF = ('', 'NULL', 'null', 'NA') EMPTY_FIELD_AS_NULL = TRUE TRIM_SPACE = TRUE COMPRESSION = AUTO;

CREATE STAGE IF NOT EXISTS STG_SYNPUF FILE_FORMAT = FF_CSV_HEADER;

-- PUT your local CSVs. Adjust paths for your machine.
PUT 'file://E:/data/synpuf/sample_01/csv/DE1_0_2008_Beneficiary_Summary_File_Sample_1.csv'          @STG_SYNPUF AUTO_COMPRESS=TRUE PARALLEL=4 OVERWRITE=TRUE;
PUT 'file://E:/data/synpuf/sample_01/csv/DE1_0_2009_Beneficiary_Summary_File_Sample_1.csv'          @STG_SYNPUF AUTO_COMPRESS=TRUE PARALLEL=4 OVERWRITE=TRUE;
PUT 'file://E:/data/synpuf/sample_01/csv/DE1_0_2010_Beneficiary_Summary_File_Sample_1.csv'          @STG_SYNPUF AUTO_COMPRESS=TRUE PARALLEL=4 OVERWRITE=TRUE;
PUT 'file://E:/data/synpuf/sample_01/csv/DE1_0_2008_to_2010_Inpatient_Claims_Sample_1.csv'          @STG_SYNPUF AUTO_COMPRESS=TRUE PARALLEL=4 OVERWRITE=TRUE;
PUT 'file://E:/data/synpuf/sample_01/csv/DE1_0_2008_to_2010_Outpatient_Claims_Sample_1.csv'         @STG_SYNPUF AUTO_COMPRESS=TRUE PARALLEL=4 OVERWRITE=TRUE;
PUT 'file://E:/data/synpuf/sample_01/csv/DE1_0_2008_to_2010_Carrier_Claims_Sample_1A.csv'           @STG_SYNPUF AUTO_COMPRESS=TRUE PARALLEL=4 OVERWRITE=TRUE;
PUT 'file://E:/data/synpuf/sample_01/csv/DE1_0_2008_to_2010_Carrier_Claims_Sample_1B.csv'           @STG_SYNPUF AUTO_COMPRESS=TRUE PARALLEL=4 OVERWRITE=TRUE;
PUT 'file://E:/data/synpuf/sample_01/csv/DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_1.csv'  @STG_SYNPUF AUTO_COMPRESS=TRUE PARALLEL=4 OVERWRITE=TRUE;
