-- Create the 7 raw tables and load them from @STG_SYNPUF.
-- Schema is inferred from each CSV's header row.

USE ROLE ACCOUNTADMIN;
USE DATABASE MA_PAYER;
USE SCHEMA RAW_SYNPUF;
USE WAREHOUSE WH_XS;

-- Beneficiary summary (one file per year)

CREATE OR REPLACE TABLE BENEFICIARY_2008
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(
        LOCATION    => '@STG_SYNPUF/DE1_0_2008_Beneficiary_Summary_File_Sample_1.csv.gz',
        FILE_FORMAT => 'FF_CSV_HEADER'
    ))
);

COPY INTO BENEFICIARY_2008
FROM @STG_SYNPUF/DE1_0_2008_Beneficiary_Summary_File_Sample_1.csv.gz
FILE_FORMAT          = (FORMAT_NAME = FF_CSV_HEADER)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR             = 'CONTINUE';


CREATE OR REPLACE TABLE BENEFICIARY_2009
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(
        LOCATION    => '@STG_SYNPUF/DE1_0_2009_Beneficiary_Summary_File_Sample_1.csv.gz',
        FILE_FORMAT => 'FF_CSV_HEADER'
    ))
);

COPY INTO BENEFICIARY_2009
FROM @STG_SYNPUF/DE1_0_2009_Beneficiary_Summary_File_Sample_1.csv.gz
FILE_FORMAT          = (FORMAT_NAME = FF_CSV_HEADER)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR             = 'CONTINUE';


CREATE OR REPLACE TABLE BENEFICIARY_2010
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(
        LOCATION    => '@STG_SYNPUF/DE1_0_2010_Beneficiary_Summary_File_Sample_1.csv.gz',
        FILE_FORMAT => 'FF_CSV_HEADER'
    ))
);

COPY INTO BENEFICIARY_2010
FROM @STG_SYNPUF/DE1_0_2010_Beneficiary_Summary_File_Sample_1.csv.gz
FILE_FORMAT          = (FORMAT_NAME = FF_CSV_HEADER)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR             = 'CONTINUE';


-- Inpatient claims

CREATE OR REPLACE TABLE INPATIENT_CLAIMS
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(
        LOCATION    => '@STG_SYNPUF/DE1_0_2008_to_2010_Inpatient_Claims_Sample_1.csv.gz',
        FILE_FORMAT => 'FF_CSV_HEADER'
    ))
);

COPY INTO INPATIENT_CLAIMS
FROM @STG_SYNPUF/DE1_0_2008_to_2010_Inpatient_Claims_Sample_1.csv.gz
FILE_FORMAT          = (FORMAT_NAME = FF_CSV_HEADER)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR             = 'CONTINUE';


-- Outpatient claims

CREATE OR REPLACE TABLE OUTPATIENT_CLAIMS
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(
        LOCATION    => '@STG_SYNPUF/DE1_0_2008_to_2010_Outpatient_Claims_Sample_1.csv.gz',
        FILE_FORMAT => 'FF_CSV_HEADER'
    ))
);

COPY INTO OUTPATIENT_CLAIMS
FROM @STG_SYNPUF/DE1_0_2008_to_2010_Outpatient_Claims_Sample_1.csv.gz
FILE_FORMAT          = (FORMAT_NAME = FF_CSV_HEADER)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR             = 'CONTINUE';


-- Carrier claims (loaded from two files: Sample_1A and Sample_1B)

CREATE OR REPLACE TABLE CARRIER_CLAIMS
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(
        LOCATION    => '@STG_SYNPUF/DE1_0_2008_to_2010_Carrier_Claims_Sample_1A.csv.gz',
        FILE_FORMAT => 'FF_CSV_HEADER'
    ))
);

COPY INTO CARRIER_CLAIMS
FROM @STG_SYNPUF/DE1_0_2008_to_2010_Carrier_Claims_Sample_1A.csv.gz
FILE_FORMAT          = (FORMAT_NAME = FF_CSV_HEADER)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR             = 'CONTINUE';

COPY INTO CARRIER_CLAIMS
FROM @STG_SYNPUF/DE1_0_2008_to_2010_Carrier_Claims_Sample_1B.csv.gz
FILE_FORMAT          = (FORMAT_NAME = FF_CSV_HEADER)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR             = 'CONTINUE';


-- Prescription drug events

CREATE OR REPLACE TABLE PRESCRIPTION_DRUG_EVENTS
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(INFER_SCHEMA(
        LOCATION    => '@STG_SYNPUF/DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_1.csv.gz',
        FILE_FORMAT => 'FF_CSV_HEADER'
    ))
);

COPY INTO PRESCRIPTION_DRUG_EVENTS
FROM @STG_SYNPUF/DE1_0_2008_to_2010_Prescription_Drug_Events_Sample_1.csv.gz
FILE_FORMAT          = (FORMAT_NAME = FF_CSV_HEADER)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR             = 'CONTINUE';


-- Row-count check against CMS-published SynPUF Sample 1 totals

SELECT 'BENEFICIARY_2008'         AS t, COUNT(*) AS row_count, 116352 AS expected FROM BENEFICIARY_2008
UNION ALL
SELECT 'BENEFICIARY_2009'              , COUNT(*)       ,  114538            FROM BENEFICIARY_2009
UNION ALL
SELECT 'BENEFICIARY_2010'              , COUNT(*)       ,  112137            FROM BENEFICIARY_2010
UNION ALL
SELECT 'INPATIENT_CLAIMS'              , COUNT(*)       ,   66773            FROM INPATIENT_CLAIMS
UNION ALL
SELECT 'OUTPATIENT_CLAIMS'             , COUNT(*)       ,  790790            FROM OUTPATIENT_CLAIMS
UNION ALL
SELECT 'CARRIER_CLAIMS'                , COUNT(*)       , 5209572            FROM CARRIER_CLAIMS
UNION ALL
SELECT 'PRESCRIPTION_DRUG_EVENTS'      , COUNT(*)       , 3418797            FROM PRESCRIPTION_DRUG_EVENTS
ORDER BY t;
