-- Role separation for this project.
-- MA_PAYER_DEV     -> dbt (read RAW, read/write STAGING + MARTS)
-- MA_PAYER_VIEWER  -> Streamlit (read-only on MARTS)
-- Run once as ACCOUNTADMIN.

USE ROLE ACCOUNTADMIN;
USE DATABASE MA_PAYER;

-- Roles
CREATE ROLE IF NOT EXISTS MA_PAYER_DEV;
CREATE ROLE IF NOT EXISTS MA_PAYER_VIEWER;

-- Warehouse
GRANT USAGE ON WAREHOUSE WH_XS TO ROLE MA_PAYER_DEV;
GRANT USAGE ON WAREHOUSE WH_XS TO ROLE MA_PAYER_VIEWER;

-- Dev role: read RAW, read/write STAGING + MARTS
GRANT USAGE ON DATABASE MA_PAYER TO ROLE MA_PAYER_DEV;

GRANT USAGE ON SCHEMA MA_PAYER.RAW_SYNPUF TO ROLE MA_PAYER_DEV;
GRANT SELECT ON ALL TABLES    IN SCHEMA MA_PAYER.RAW_SYNPUF TO ROLE MA_PAYER_DEV;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MA_PAYER.RAW_SYNPUF TO ROLE MA_PAYER_DEV;

GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA MA_PAYER.STAGING TO ROLE MA_PAYER_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES    IN SCHEMA MA_PAYER.STAGING TO ROLE MA_PAYER_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA MA_PAYER.STAGING TO ROLE MA_PAYER_DEV;
GRANT SELECT ON ALL VIEWS    IN SCHEMA MA_PAYER.STAGING TO ROLE MA_PAYER_DEV;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MA_PAYER.STAGING TO ROLE MA_PAYER_DEV;

GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA MA_PAYER.MARTS TO ROLE MA_PAYER_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES    IN SCHEMA MA_PAYER.MARTS TO ROLE MA_PAYER_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA MA_PAYER.MARTS TO ROLE MA_PAYER_DEV;
GRANT SELECT ON ALL VIEWS    IN SCHEMA MA_PAYER.MARTS TO ROLE MA_PAYER_DEV;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MA_PAYER.MARTS TO ROLE MA_PAYER_DEV;

-- Viewer role: read-only on MARTS
GRANT USAGE ON DATABASE MA_PAYER       TO ROLE MA_PAYER_VIEWER;
GRANT USAGE ON SCHEMA   MA_PAYER.MARTS TO ROLE MA_PAYER_VIEWER;
GRANT SELECT ON ALL TABLES    IN SCHEMA MA_PAYER.MARTS TO ROLE MA_PAYER_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MA_PAYER.MARTS TO ROLE MA_PAYER_VIEWER;
GRANT SELECT ON ALL VIEWS     IN SCHEMA MA_PAYER.MARTS TO ROLE MA_PAYER_VIEWER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA MA_PAYER.MARTS TO ROLE MA_PAYER_VIEWER;

-- Service users.
-- For DBT_SVC, prefer RSA_PUBLIC_KEY over PASSWORD (see docs/auth-setup.md).
-- Replace placeholders before running.
CREATE USER IF NOT EXISTS DBT_SVC
    PASSWORD          = '<set strong password or use ALTER USER ... SET RSA_PUBLIC_KEY>'
    DEFAULT_ROLE      = MA_PAYER_DEV
    DEFAULT_WAREHOUSE = WH_XS
    DEFAULT_NAMESPACE = MA_PAYER.STAGING;

CREATE USER IF NOT EXISTS APP_SVC
    PASSWORD          = '<set strong password>'
    DEFAULT_ROLE      = MA_PAYER_VIEWER
    DEFAULT_WAREHOUSE = WH_XS
    DEFAULT_NAMESPACE = MA_PAYER.MARTS;

GRANT ROLE MA_PAYER_DEV    TO USER DBT_SVC;
GRANT ROLE MA_PAYER_VIEWER TO USER APP_SVC;

-- Check
SHOW GRANTS TO ROLE MA_PAYER_DEV;
SHOW GRANTS TO ROLE MA_PAYER_VIEWER;
